Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'app/admin/**/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
